name: fds-local
services:
  trainhandler-client:
    image: fairdata/trainhandler-client:develop
    restart: unless-stopped
    ports:
      # bound to 127.0.0.1 (localhost) to prevent exposing to public internet
      - "127.0.0.1:3000:3000"
    environment:
      NUXT_PUBLIC_API_URL: http://localhost:8080
      NUXT_PUBLIC_KEYCLOAK_URL: http://localhost:8085
      NUXT_PUBLIC_KEYCLOAK_REALM: fdt
      NUXT_PUBLIC_KEYCLOAK_CLIENT_ID: trainhandler-client
     # NUXT_PUBLIC_KEYCLOAK_DISABLED: true

  trainhandler-server:
    image: fairdata/trainhandler-server:develop
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./trainhandler.application.yml:/app/application.yml:ro

  fds:
    image: fairdata/fairdatastation:develop
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8080"
    depends_on:
      - postgres
    volumes:
      - ./fds.application.yml:/app/application.yml:ro

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    command: start
    ports:
      - "127.0.0.1:8085:8085"
    depends_on:
      - postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      #KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost:8085
      PROXY_ADDRESS_FORWARDING: true
      KC_PROXY: edge
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 8085
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT: false

  postgres:
    image: postgres:15.1
    ports:
      - "127.0.0.1:54321:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/00-init.sql
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  postgresdata:
