data-station:
  # not needed now
  fdp-url: http://fdp

  # as in FDP
  storages:
    triple-store:
      # valid repository type options {1 = inMemoryStore, 2 = NativeStore, 3 = AllegroGraph, 4 = graphDB, 5 = blazegraph}
      type: 1
      native:
        dir: /tmp/fdp-store/
      agraph:
        url: http://localhost:10035/repositories/fdp
        username: user
        password: password
      graphDb:
        url: http://localhost:7200
        repository: test
      blazegraph:
        url: http://localhost:8888/blazegraph
        repository:

spring:
  datasource:
    url: jdbc:postgresql://postgres/fds
    username: postgres
    password: password
